insert into salesman (salesman_id, name, city, commission) values (1, 'Kiele', 'Timashëvsk', 0.14);
insert into salesman (salesman_id, name, city, commission) values (2, 'Lambert', 'Ternopil’', 0.36);
insert into salesman (salesman_id, name, city, commission) values (3, 'Valenka', 'Santa Catalina', 0.89);
insert into salesman (salesman_id, name, city, commission) values (4, 'Horace', 'Huayang', 0.13);
insert into salesman (salesman_id, name, city, commission) values (5, 'Ahmad', 'La Curva', 0.74);
insert into salesman (salesman_id, name, city, commission) values (6, 'Melony', 'Huangli', 0.94);
insert into salesman (salesman_id, name, city, commission) values (7, 'Gwyneth', 'Knoxville', 0.01);
insert into salesman (salesman_id, name, city, commission) values (8, 'Auria', 'Phetchabun', 0.7);
insert into salesman (salesman_id, name, city, commission) values (9, 'Franni', 'Houping', 0.39);
insert into salesman (salesman_id, name, city, commission) values (10, 'Hamil', 'Ferrol', 0.02);
insert into salesman (salesman_id, name, city, commission) values (11, 'Carola', 'Tombu', 0.46);
insert into salesman (salesman_id, name, city, commission) values (12, 'Dorette', 'Rožna Dolina', 0.39);
insert into salesman (salesman_id, name, city, commission) values (13, 'Harp', 'Tanakawu Dua', 0.99);
insert into salesman (salesman_id, name, city, commission) values (14, 'Zachariah', 'Halayhay', 0.56);
insert into salesman (salesman_id, name, city, commission) values (15, 'Concettina', 'Xuling', 0.09);
insert into salesman (salesman_id, name, city, commission) values (16, 'Penni', 'Sann', 0.26);
insert into salesman (salesman_id, name, city, commission) values (17, 'Averill', 'Frydrychowice', 0.37);
insert into salesman (salesman_id, name, city, commission) values (18, 'Tobias', 'Pancol', 0.9);
insert into salesman (salesman_id, name, city, commission) values (19, 'Cairistiona', 'Örnsköldsvik', 0.58);
insert into salesman (salesman_id, name, city, commission) values (20, 'Isa', 'Tovarkovskiy', 0.09);
insert into salesman (salesman_id, name, city, commission) values (21, 'Farlee', 'Montalegre', 0.45);
insert into salesman (salesman_id, name, city, commission) values (22, 'Melva', 'Kosong', 0.35);
insert into salesman (salesman_id, name, city, commission) values (23, 'Wallis', 'Shuya', 0.57);
insert into salesman (salesman_id, name, city, commission) values (24, 'Astrid', 'Yonghe', 0.4);
insert into salesman (salesman_id, name, city, commission) values (25, 'Buiron', 'Nanping', 0.64);
insert into salesman (salesman_id, name, city, commission) values (26, 'Jolene', 'Sukamulia', 0.62);
insert into salesman (salesman_id, name, city, commission) values (27, 'Susana', 'Alvesta', 0.06);
insert into salesman (salesman_id, name, city, commission) values (28, 'Esteban', 'Esparza', 0.82);
insert into salesman (salesman_id, name, city, commission) values (29, 'Jenny', 'Nuamuzi', 0.99);
insert into salesman (salesman_id, name, city, commission) values (30, 'Ulrikaumeko', 'Poctol', 0.79);
insert into salesman (salesman_id, name, city, commission) values (31, 'Richard', 'Miass', 0.1);
insert into salesman (salesman_id, name, city, commission) values (32, 'Justino', 'Homagama', 0.77);
insert into salesman (salesman_id, name, city, commission) values (33, 'Carry', 'Diriamba', 0.99);
insert into salesman (salesman_id, name, city, commission) values (34, 'Kiersten', 'Haifa', 0.74);
insert into salesman (salesman_id, name, city, commission) values (35, 'Sherri', 'Changma', 0.72);
insert into salesman (salesman_id, name, city, commission) values (36, 'Julie', 'Al Nashmah', 0.6);
insert into salesman (salesman_id, name, city, commission) values (37, 'Con', 'Ręczno', 0.38);
insert into salesman (salesman_id, name, city, commission) values (38, 'Cymbre', 'Adámas', 0.15);
insert into salesman (salesman_id, name, city, commission) values (39, 'Robina', 'Jinqiao', 0.71);
insert into salesman (salesman_id, name, city, commission) values (40, 'Thedrick', 'Kaka', 0.7);
insert into salesman (salesman_id, name, city, commission) values (41, 'Karlen', 'Xincun', 0.05);
insert into salesman (salesman_id, name, city, commission) values (42, 'Elaine', 'Manosque', 0.07);
insert into salesman (salesman_id, name, city, commission) values (43, 'Wood', 'Kauman', 0.74);
insert into salesman (salesman_id, name, city, commission) values (44, 'Noak', 'Aguas del Padre', 0.11);
insert into salesman (salesman_id, name, city, commission) values (45, 'Lorne', 'Nangkapayung', 0.99);
insert into salesman (salesman_id, name, city, commission) values (46, 'Clerkclaude', 'Stará Ves nad Ondřejnicí', 0.8);
insert into salesman (salesman_id, name, city, commission) values (47, 'Sheena', 'Katuli', 0.61);
insert into salesman (salesman_id, name, city, commission) values (48, 'Isaak', 'Kastsyukovichy', 0.7);
insert into salesman (salesman_id, name, city, commission) values (49, 'Rivy', 'Santa Lucía', 0.18);
insert into salesman (salesman_id, name, city, commission) values (50, 'Cristian', 'Méru', 0.13);
insert into salesman (salesman_id, name, city, commission) values (51, 'Gray', 'Bombarral', 0.27);
insert into salesman (salesman_id, name, city, commission) values (52, 'Brant', 'Hyesan-dong', 0.36);
insert into salesman (salesman_id, name, city, commission) values (53, 'Melisenda', 'Helsingborg', 0.13);
insert into salesman (salesman_id, name, city, commission) values (54, 'Alane', 'Carcassonne', 0.7);
insert into salesman (salesman_id, name, city, commission) values (55, 'Dukie', 'Kwekwe', 0.5);
insert into salesman (salesman_id, name, city, commission) values (56, 'Chadwick', 'Al Bahlūlīyah', 0.03);
insert into salesman (salesman_id, name, city, commission) values (57, 'Ode', 'Derjan', 0.8);
insert into salesman (salesman_id, name, city, commission) values (58, 'Desiree', 'Samir', 0.27);
insert into salesman (salesman_id, name, city, commission) values (59, 'Damien', 'Chunhu', 0.12);
insert into salesman (salesman_id, name, city, commission) values (60, 'Beatrice', 'Baltiysk', 0.44);
insert into salesman (salesman_id, name, city, commission) values (61, 'Lauryn', 'Dianya', 0.99);
insert into salesman (salesman_id, name, city, commission) values (62, 'Janela', 'Al Miftāḩ', 0.84);
insert into salesman (salesman_id, name, city, commission) values (63, 'Milzie', 'Hexi', 0.49);
insert into salesman (salesman_id, name, city, commission) values (64, 'Manfred', 'Kuala Lumpur', 0.92);
insert into salesman (salesman_id, name, city, commission) values (65, 'Jinny', 'Vänersborg', 0.65);
insert into salesman (salesman_id, name, city, commission) values (66, 'Edan', 'Klášter', 0.49);
insert into salesman (salesman_id, name, city, commission) values (67, 'Margareta', 'Jiguan', 0.11);
insert into salesman (salesman_id, name, city, commission) values (68, 'Matty', 'Pokrovskoye', 1.0);
insert into salesman (salesman_id, name, city, commission) values (69, 'Griffith', 'Đưc Trọng', 0.55);
insert into salesman (salesman_id, name, city, commission) values (70, 'Brunhilda', 'Крушево', 0.08);
insert into salesman (salesman_id, name, city, commission) values (71, 'Tabor', 'Elato', 0.08);
insert into salesman (salesman_id, name, city, commission) values (72, 'Fawne', 'Singosari', 0.18);
insert into salesman (salesman_id, name, city, commission) values (73, 'Dino', 'Tevriz', 0.45);
insert into salesman (salesman_id, name, city, commission) values (74, 'Nefen', 'Huangfang', 0.51);
insert into salesman (salesman_id, name, city, commission) values (75, 'Sterling', 'Nyinqug', 0.72);
insert into salesman (salesman_id, name, city, commission) values (76, 'Karlis', 'Ambat', 0.29);
insert into salesman (salesman_id, name, city, commission) values (77, 'Farlee', 'Gyumri', 0.57);
insert into salesman (salesman_id, name, city, commission) values (78, 'Nanni', 'Cà Mau', 0.6);
insert into salesman (salesman_id, name, city, commission) values (79, 'Pembroke', 'El Zulia', 0.2);
insert into salesman (salesman_id, name, city, commission) values (80, 'Wynny', 'Federal', 0.08);
insert into salesman (salesman_id, name, city, commission) values (81, 'Patrizio', 'Rembes', 0.17);
insert into salesman (salesman_id, name, city, commission) values (82, 'Liam', 'Guyi', 0.73);
insert into salesman (salesman_id, name, city, commission) values (83, 'Gnni', 'Cam Ranh', 0.54);
insert into salesman (salesman_id, name, city, commission) values (84, 'Byram', 'Anguil', 0.81);
insert into salesman (salesman_id, name, city, commission) values (85, 'Tybi', 'Waterloo', 0.23);
insert into salesman (salesman_id, name, city, commission) values (86, 'Smith', 'Migues', 0.93);
insert into salesman (salesman_id, name, city, commission) values (87, 'Karylin', 'Fílla', 0.36);
insert into salesman (salesman_id, name, city, commission) values (88, 'Faith', 'Chernyshevsk', 1.0);
insert into salesman (salesman_id, name, city, commission) values (89, 'Karil', 'Fujikawaguchiko', 0.36);
insert into salesman (salesman_id, name, city, commission) values (90, 'Shelly', 'Fier', 0.73);
insert into salesman (salesman_id, name, city, commission) values (91, 'Enrichetta', 'Juhaynah', 0.36);
insert into salesman (salesman_id, name, city, commission) values (92, 'Corrie', 'Almeria', 0.05);
insert into salesman (salesman_id, name, city, commission) values (93, 'Goldi', 'Caramanta', 0.55);
insert into salesman (salesman_id, name, city, commission) values (94, 'Mateo', 'Dawang', 0.52);
insert into salesman (salesman_id, name, city, commission) values (95, 'Alastair', 'Piripiri', 0.26);
insert into salesman (salesman_id, name, city, commission) values (96, 'Zebadiah', 'Ciasna', 0.94);
insert into salesman (salesman_id, name, city, commission) values (97, 'Arman', 'Foz Sousa', 0.68);
insert into salesman (salesman_id, name, city, commission) values (98, 'Francklin', 'Estancia', 0.55);
insert into salesman (salesman_id, name, city, commission) values (99, 'Starlin', 'San Vicente', 0.23);
insert into salesman (salesman_id, name, city, commission) values (100, 'Dorian', 'Arcena', 0.5);
